name: Create random file.

on:
  schedule:
    - cron: '*/59 * * * *'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: intg
        token: ${{ secrets.PAT_TOKEN }}

    - name: Generate random file
      run: |
        mkdir -p contents
        echo $RANDOM > contents/random_file_$(date +%s).txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'dpagini'
        git config --global user.email 'david.pagini@voya.com'
        git add contents/
        git commit -m "Automate adding a random file."
        git push origin intg
