name: 'Create a new POC site.'
on:
  workflow_dispatch:
    inputs:
      number:
        type: string
        description: 'Site identifier #.'

env:
  TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
  PANTHEON_UPSTREAM_ID: 'c24dfe83-5182-4fd6-ade3-94884a2c8426'
  PANTHEON_ORG_ID: '06746d4c-53c3-4651-99bf-e2614ca75476'

jobs:
  create_site:
    name: 'Create new POC site on Pantheon'
    runs-on: ubuntu-latest
    env:
      SITE_ID: 'poc-ghcom-site${{ inputs.number }}'
      SITE_NAME: 'POC-GHcom-Site${{ inputs.number }}'
    steps:
      ################################ REPEATED CODE ############################################################################
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install Terminus
        run: |
          mkdir -p ~/terminus
          curl -L https://github.com/pantheon-systems/terminus/releases/download/$(curl -s https://api.github.com/repos/pantheon-systems/terminus/releases/latest | grep tag_name | cut -d '"' -f 4)/terminus.phar -o ~/terminus/terminus
          chmod +x ~/terminus/terminus
          sudo ln -s ~/terminus/terminus /usr/local/bin/terminus
      - name: Authenticate Terminus
        run: terminus auth:login --machine-token="$TERMINUS_TOKEN"
      ###########################################################################################################################
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PANTHEON_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - name: Start SSH agent and add key
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      ###########################################################################################################################
      - run: |
          terminus site:create --org $PANTHEON_ORG_ID --region US -- $SITE_ID "$SITE_NAME" $PANTHEON_UPSTREAM_ID
          terminus tag:add $SITE_ID $PANTHEON_ORG_ID "ghpoc"
          terminus multidev:create --no-db --no-files -- $SITE_ID.dev intg

          # Install the INTG environment. This ensures auto-deploys work as designed.
          terminus drush $SITE_ID.intg -- site:install demo_umami -n
          terminus drush $SITE_ID.intg -- cr

          echo "### Your new site is ready!! :rocket:" >> $GITHUB_STEP_SUMMARY
